### ISSUE TITLE
BehaviourParam_PC issue

### ISSUE THREAD

**Issue by Kage8888** [ividyon/WitchyBND#11]
BehaviourParam_PC extracts just fine, no issues detected.
Putting that same, unedited param back into the game causes the weapon behaviours to break: no sound, no projectiles, no damage.

**Comment by ividyon** [comment]
Thank you. As per the Nexus page (I should probably write it here too):

![2023-09-03_16-45-29__chrome](https://github.com/ividyon/WitchyBND/assets/1077140/7b8d212a-e9ae-4e7f-a39f-8c353e87d76c)

The param definitions for AC6 are in progress, so issues like this will occur for a while. I forwarded the information to those who work on the paramdefs.

**Comment by ividyon** [comment]
@Kage8888 Do you have your "round tripped" version of BehaviorParam_PC for me?

**Comment by Kage8888** [comment]
[BehaviorParam_PC.zip](https://github.com/ividyon/WitchyBND/files/12507405/BehaviorParam_PC.zip)
Freshly made, reproduced the issue exactly as before. 

Removing it fixes the entire regulation, and changes made to the behaviour param that edit fire rate do appear to be processed, even though the actual sfx/atk data doesn't seem to come into existence.

**Comment by ividyon** [comment]
@Kage8888 A new release has just been made, could you please confirm the issue is resolved?

It had to do with the tentative paramdef having duplicate names for param fields, which I used to separate by SortID, but unofficial paramdefs do not have a SortID value, so I'm using the byte offset now.

**Comment by Kage8888** [comment]
Confirmed the new release addresses the issue. Flying colours, thank you.

Have some notes:

ThrustersParam_PC - Unk0x68 = QB dodge thrust
ThrustersParam_PC - Unk0x70 = QB dodge cost
ThrustersParam_PC - Unk0x74 = Up thrust
ThrustersParam_PC - Unk0x78 = Up cost

BehaviourParamPC - Unk0x54 = Rate of Fire

EquipWeaponParam - Unk0x308 = WepMotionCategory

AttackActionParamPC - Unk0x4C = Set to 0 to prevent weapons bringing AC to a stop (and disabling boost) to fire. Best results with switched WepMotionCategory.
Current example of the Unk0x4C flag is change the GOU CHEN by way of setting Unk0x308=205 (shotgun) in equipweaponparam, and setting Unk0x4C="0" in AttackActionParam_PC.
