### ISSUE TITLE
witchybnd.dcx.exe cannot handle .tpf.dcx

### ISSUE THREAD

**Issue by sonofevil** [ividyon/WitchyBND#16]
I want to decompress a .tpf.dcx file from Demon's Souls. But WitchyBND.dcx.exe gives me this error:

`XML file not found: D:\users\lutra\Desktop\projects\modding\DeS\textures\map\m01\dcx\m01_9999.tpf.dcx-wbinder-dcx.xml                                                                                                                           One or more errors were encountered and displayed above.                                                                Press any key to exit.  `  

It looks to me like WitchyBND.dcx does not recognize .tpf.dcx as a .dcx file because it expects bnd.dcx. But in DeS that isn't universal.

So when I give it a .tpf.dcx file, instead of decompressing it, it tries to compress it, but does not find an xml.

**Comment by sonofevil** [comment]
Nvm, I'm dumb.

**Comment by ividyon** [comment]
@sonofevil FYI there is no longer a DCX.exe in the latest version.
