### ISSUE TITLE
Incorrect file header for AC6 save files

### ISSUE THREAD

**Issue by meshal-h** [ividyon/WitchyBND#17]
When I tried to unpack and then repack an [AC6 save file](https://www.nexusmods.com/armoredcore6firesofrubicon/mods/19) (without any edits), I noticed that the header of the repacked file did not match the original file:

![AC6](https://github.com/ividyon/WitchyBND/assets/87278266/8255099d-2ac0-4bff-a2f1-b85d9a1907a2)

The game can read the repacked file but it can not modify it ("Failed to save game due to corrupted save data." error whenever the game tries to save new data).

Did I miss something? I simply dragged and dropped the file/folder on the exe. Or are AC6 .sl2 save files not supported?

**Comment by ividyon** [comment]
It's more that nobody tried them out before you. Seems there's some kind of incompatibility! I'll try to make time sometime...

**Comment by meshal-h** [comment]
It works! Thank you for the update.
