### ISSUE TITLE
Missing canMountWep Fields For EquipParamGem For New DLC Weapon Types

### ISSUE THREAD

**Issue by cozzbp** [ividyon/WitchyBND#28]
Missing defs for new Weapon types:
https://github.com/ividyon/WitchyBND/blob/c618b01efae3f1a01bfa5c7091c0e26e91c56355/WitchyBND/Assets/Paramdex/ER/Defs/EquipParamGem.xml#L524

Hand to Hand
Perfume Bottle
Thrusting Shield
Throwing Blade
Backhand Blade
Light Greatsword
Great Katana
Beast Claw

**Comment by ividyon** [comment]
You can make contributions for field definitions over at Smithbox, where I'm taking my param definitions from.
