### ISSUE TITLE
Unable to unpack a regulation.bin file

### ISSUE THREAD

**Issue by heyhowareyoubro** [ividyon/WitchyBND#31]
Hey I recently downloaded a mod wanted to check out few stuff in the regulation.bin file but was unable to view it. I thought of unpacking the params but was unable to do it on the v2.12.0.0 version. Could you help please? 
![Capturvve](https://github.com/user-attachments/assets/31fbc385-57da-4ad4-8352-46adc42bc12d)

**Comment by ividyon** [comment]
Seems like a Chinese mod I was told about that does something to prevents tools from reading it. What mod is it, and where did you acquire it?

**Comment by heyhowareyoubro** [comment]
I acquired the mod from Pan Baidu and yes it's a chinese mod! Also mod's name is in Chinese so can't really tell but it is a moveset modpack. I found the link from bilibili website.

**Comment by ividyon** [comment]
Well, having the complete thing would help research this, until then I can't do much here I don't think.

**Comment by heyhowareyoubro** [comment]
I don't mind providing you the complete thing but after research I heard a tool named Binder was able to do it and I saw he wrote some tips to unpack encrypted stuff maybe that could be of help. https://github.com/Atvaark/BinderTool
