### ISSUE TITLE
Failed to repack bnd file

### ISSUE THREAD

**Issue by colaaaaaa123** [ividyon/WitchyBND#36]
When I repack a partsbnd file, WitchyBND throws an error message: "WitchyBND could not operate on the file as it is locked by another process: Could not find file '……\parts\bd_m_9010.partsbnd.undcx-wbinder-dcx.xml'." This is because Witchy's XML file is "bd_m_9010.partsbnd-wbinder-dcx", not "bd_m_9010.partsbnd.undcx-wbinder-dcx.xml" lol.
Thanks for your work ❤

**Comment by ividyon** [comment]
@colaaaaaa123 This seems to work for me. Are you on the latest release?
